### PR TITLE
landing page revamp attempt

### PR DESCRIPTION
**Pull request by PrincetonPoh**
I used https://github.com/papercss/papercss for the elements.

Not sure if the font is readable though....but it looks nice on the landing page HAHHAHA

Loose ends:
- [x] Pick better images? 
- [x] Make sure the images have the same aspect ratio and size
- [x] The form at the bottom doesnt really submit to anywhere HAHAHAHA
- [x] Dark theme header is abit off
- [ ] Build the subsequent pages once ppl click into project dojo/optic....right now they cant click into anything
- [ ] Improve the copywriting
- [x] Maybe download papercss instead of using the CDN
- [x] Breadcrumbs seems to be broken or not working from the beginning? (top left header of screen)

### CODE REVIEW

**Comment by PrincetonPoh** [comment]
side note, why arent we using tailwind? :'))

but it's ok, i'll just @media everywhere HAHAHAHA

**Comment by PrincetonPoh** [comment]
Also, am I suppose to be writing so much html and css inside of the markdown? HAHAHAHA

i just did what works to get a feel first...lmk if design is dog shit or not

**Comment by ks0m1c** [comment]
> side note, why arent we using tailwind? :'))
> 
> but it's ok, i'll just @media everywhere HAHAHAHA

lmaoo its easy to integrate tailwind 

https://mzrn.sh/2022/04/09/starting-a-blank-jekyll-site-with-tailwind-css-in-2022

**Comment by PrincetonPoh** [comment]
image

@ks0m1c your notes_graph is adding a rando <g> into the logo.

image

**Review by PrincetonPoh — COMMENTED** [review]
@ks0m1c this commit broke the interlinked map at the bottom of a blog post

**Comment by PrincetonPoh** [comment]
@ks0m1c If i add `<a hef="">` to the project dojo cards, the formatting goes haywire. "all: unset" doesnt seem to be an option. Please see what u can do to help with doing the linking.

**Pull request merged**
